/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LandRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "admin"
      | "authorizeTransfer"
      | "cancelTransfer"
      | "getLand"
      | "getLandIdByIndex"
      | "getTotalLandsCount"
      | "getTransferRequest"
      | "governmentVerifier"
      | "initiateTransfer"
      | "landExists"
      | "registerLand"
      | "rejectTransfer"
      | "setGovernmentVerifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GovernmentVerifierUpdated"
      | "LandRegistered"
      | "OwnershipTransferred"
      | "TransferAccepted"
      | "TransferCancelled"
      | "TransferInitiated"
      | "TransferRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransfer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getLand", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getLandIdByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalLandsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferRequest",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "governmentVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "landExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerLand",
    values: [string, string, AddressLike, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernmentVerifier",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLandIdByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalLandsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governmentVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "landExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernmentVerifier",
    data: BytesLike
  ): Result;
}

export namespace GovernmentVerifierUpdatedEvent {
  export type InputTuple = [
    previousVerifier: AddressLike,
    newVerifier: AddressLike
  ];
  export type OutputTuple = [previousVerifier: string, newVerifier: string];
  export interface OutputObject {
    previousVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LandRegisteredEvent {
  export type InputTuple = [
    landIdIndexed: string,
    landId: string,
    parcelNumber: string,
    owner: AddressLike,
    verifier: AddressLike,
    registeredAt: BigNumberish,
    docHash: string
  ];
  export type OutputTuple = [
    landIdIndexed: string,
    landId: string,
    parcelNumber: string,
    owner: string,
    verifier: string,
    registeredAt: bigint,
    docHash: string
  ];
  export interface OutputObject {
    landIdIndexed: string;
    landId: string;
    parcelNumber: string;
    owner: string;
    verifier: string;
    registeredAt: bigint;
    docHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    landIdIndexed: string,
    landId: string,
    previousOwner: AddressLike,
    newOwner: AddressLike,
    verifier: AddressLike,
    completedAt: BigNumberish
  ];
  export type OutputTuple = [
    landIdIndexed: string,
    landId: string,
    previousOwner: string,
    newOwner: string,
    verifier: string,
    completedAt: bigint
  ];
  export interface OutputObject {
    landIdIndexed: string;
    landId: string;
    previousOwner: string;
    newOwner: string;
    verifier: string;
    completedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcceptedEvent {
  export type InputTuple = [
    landIdIndexed: string,
    landId: string,
    buyer: AddressLike,
    acceptedAt: BigNumberish
  ];
  export type OutputTuple = [
    landIdIndexed: string,
    landId: string,
    buyer: string,
    acceptedAt: bigint
  ];
  export interface OutputObject {
    landIdIndexed: string;
    landId: string;
    buyer: string;
    acceptedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferCancelledEvent {
  export type InputTuple = [
    landIdIndexed: string,
    landId: string,
    seller: AddressLike,
    cancelledAt: BigNumberish
  ];
  export type OutputTuple = [
    landIdIndexed: string,
    landId: string,
    seller: string,
    cancelledAt: bigint
  ];
  export interface OutputObject {
    landIdIndexed: string;
    landId: string;
    seller: string;
    cancelledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    landIdIndexed: string,
    landId: string,
    seller: AddressLike,
    proposedBuyer: AddressLike,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    landIdIndexed: string,
    landId: string,
    seller: string,
    proposedBuyer: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    landIdIndexed: string;
    landId: string;
    seller: string;
    proposedBuyer: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRejectedEvent {
  export type InputTuple = [
    landIdIndexed: string,
    landId: string,
    buyer: AddressLike,
    rejectedAt: BigNumberish
  ];
  export type OutputTuple = [
    landIdIndexed: string,
    landId: string,
    buyer: string,
    rejectedAt: bigint
  ];
  export interface OutputObject {
    landIdIndexed: string;
    landId: string;
    buyer: string;
    rejectedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<[landId: string], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  authorizeTransfer: TypedContractMethod<
    [landId: string],
    [void],
    "nonpayable"
  >;

  cancelTransfer: TypedContractMethod<[landId: string], [void], "nonpayable">;

  getLand: TypedContractMethod<
    [landId: string],
    [
      [
        string,
        string,
        string,
        boolean,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: string;
        parcelNumber: string;
        currentOwner: string;
        isVerified: boolean;
        registeredAt: bigint;
        locality: string;
        areaSqMeters: bigint;
        docHash: string;
        transferCount: bigint;
      }
    ],
    "view"
  >;

  getLandIdByIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getTotalLandsCount: TypedContractMethod<[], [bigint], "view">;

  getTransferRequest: TypedContractMethod<
    [landId: string],
    [
      [string, string, bigint, bigint, bigint] & {
        seller: string;
        proposedBuyer: string;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  governmentVerifier: TypedContractMethod<[], [string], "view">;

  initiateTransfer: TypedContractMethod<
    [landId: string, proposedBuyer: AddressLike],
    [void],
    "nonpayable"
  >;

  landExists: TypedContractMethod<[landId: string], [boolean], "view">;

  registerLand: TypedContractMethod<
    [
      landId: string,
      parcelNumber: string,
      ownerWallet: AddressLike,
      locality: string,
      areaSqMeters: BigNumberish,
      docHash: string
    ],
    [void],
    "nonpayable"
  >;

  rejectTransfer: TypedContractMethod<[landId: string], [void], "nonpayable">;

  setGovernmentVerifier: TypedContractMethod<
    [_newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[landId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeTransfer"
  ): TypedContractMethod<[landId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTransfer"
  ): TypedContractMethod<[landId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLand"
  ): TypedContractMethod<
    [landId: string],
    [
      [
        string,
        string,
        string,
        boolean,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: string;
        parcelNumber: string;
        currentOwner: string;
        isVerified: boolean;
        registeredAt: bigint;
        locality: string;
        areaSqMeters: bigint;
        docHash: string;
        transferCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLandIdByIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalLandsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransferRequest"
  ): TypedContractMethod<
    [landId: string],
    [
      [string, string, bigint, bigint, bigint] & {
        seller: string;
        proposedBuyer: string;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "governmentVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [landId: string, proposedBuyer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "landExists"
  ): TypedContractMethod<[landId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerLand"
  ): TypedContractMethod<
    [
      landId: string,
      parcelNumber: string,
      ownerWallet: AddressLike,
      locality: string,
      areaSqMeters: BigNumberish,
      docHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectTransfer"
  ): TypedContractMethod<[landId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGovernmentVerifier"
  ): TypedContractMethod<[_newVerifier: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "GovernmentVerifierUpdated"
  ): TypedContractEvent<
    GovernmentVerifierUpdatedEvent.InputTuple,
    GovernmentVerifierUpdatedEvent.OutputTuple,
    GovernmentVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LandRegistered"
  ): TypedContractEvent<
    LandRegisteredEvent.InputTuple,
    LandRegisteredEvent.OutputTuple,
    LandRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TransferAccepted"
  ): TypedContractEvent<
    TransferAcceptedEvent.InputTuple,
    TransferAcceptedEvent.OutputTuple,
    TransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferCancelled"
  ): TypedContractEvent<
    TransferCancelledEvent.InputTuple,
    TransferCancelledEvent.OutputTuple,
    TransferCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRejected"
  ): TypedContractEvent<
    TransferRejectedEvent.InputTuple,
    TransferRejectedEvent.OutputTuple,
    TransferRejectedEvent.OutputObject
  >;

  filters: {
    "GovernmentVerifierUpdated(address,address)": TypedContractEvent<
      GovernmentVerifierUpdatedEvent.InputTuple,
      GovernmentVerifierUpdatedEvent.OutputTuple,
      GovernmentVerifierUpdatedEvent.OutputObject
    >;
    GovernmentVerifierUpdated: TypedContractEvent<
      GovernmentVerifierUpdatedEvent.InputTuple,
      GovernmentVerifierUpdatedEvent.OutputTuple,
      GovernmentVerifierUpdatedEvent.OutputObject
    >;

    "LandRegistered(string,string,string,address,address,uint256,string)": TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;
    LandRegistered: TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(string,string,address,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TransferAccepted(string,string,address,uint256)": TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;
    TransferAccepted: TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;

    "TransferCancelled(string,string,address,uint256)": TypedContractEvent<
      TransferCancelledEvent.InputTuple,
      TransferCancelledEvent.OutputTuple,
      TransferCancelledEvent.OutputObject
    >;
    TransferCancelled: TypedContractEvent<
      TransferCancelledEvent.InputTuple,
      TransferCancelledEvent.OutputTuple,
      TransferCancelledEvent.OutputObject
    >;

    "TransferInitiated(string,string,address,address,uint256)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;

    "TransferRejected(string,string,address,uint256)": TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;
    TransferRejected: TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;
  };
}
